--제약조건 활성화
--INSERT INTO T_NOVALIDATE VALUES(1,'DDD');

--ALTER TABLE T_NOVALIDATE
--DISABLE NOVALIDATE CONSTRAINT SYS_C008338;

--INSERT INTO T_NOVALIDATE VALUES(1,'DDD');

SELECT * FROM T_NOVALIDATE;