COL TOTAL FOR 99

SELECT TOTAL,
	   SEOUL, GYEONGGI,BUSAN,DAEGU,GYEONGNAM
	FROM (
		SELECT SUBSTR(tel , 1, INSTR(tel, ')')-1) AS LOC,
		COUNT(tel)OVER() TOTAL
		FROM student
		)
	PIVOT (
		COUNT(LOC)
		FOR LOC IN (
	'02' AS SEOUL,
	'031' AS GYEONGGI,
	'051' AS BUSAN,
	'052' AS ULSAN,
	'053' AS DAEGU,
    '055' AS GYEONGNAM
)
)
	;