COL TOTAL FOR a12
COL SEOUL FOR a12
COL GYEONGGI FOR a12
COL BUSAN FOR a12
COL DAEGU FOR a12
COL GYEONGNAM FOR a12

SELECT TO_CHAR(TOTAL)    ||'EA' AS TOTAL,
	   TO_CHAR(SEOUL)    ||'EA' || '(' ||ROUND(SEOUL/TOTAL*100,1)    || '%)'AS SEOUL, 
	   TO_CHAR(GYEONGGI) ||'EA' || '(' ||ROUND(GYEONGGI/TOTAL*100,1) || '%)'AS GYEONGGI,
	   TO_CHAR(BUSAN)    ||'EA' || '(' ||ROUND(BUSAN/TOTAL*100,1)    || '%)'AS BUSAN,
	   TO_CHAR(DAEGU)    ||'EA' || '(' ||ROUND(DAEGU/TOTAL*100,1)    || '%)'AS DAEGU,
	   TO_CHAR(GYEONGNAM)||'EA' || '(' ||ROUND(GYEONGNAM/TOTAL*100,1)|| '%)'AS GYEONGNAM
	FROM (
		SELECT SUBSTR(tel , 1, INSTR(tel, ')')-1) AS LOC,
		COUNT(tel)OVER() TOTAL
		FROM student
		)
	PIVOT (
		COUNT(LOC)
		FOR LOC IN (
	'02' AS SEOUL,
	'031' AS GYEONGGI,
	'051' AS BUSAN,
	'052' AS ULSAN,
	'053' AS DAEGU,
    '055' AS GYEONGNAM
)
)
	;
	
