DROP INDEX PK_EXAMPLE;

/* 테이블 설계 예시 */
DROP TABLE EXAMPLE 
	CASCADE CONSTRAINTS;

/* 테이블 설계 예시 */
CREATE TABLE EXAMPLE (
	ID NUMBER(5) NOT NULL, /* 아이디 */
	NAME VARCHAR2(8) NOT NULL, /* 이름 */
	BIRTH_DATE DATE, /* 생년월일 */
	SALARY NUMBER(9) DEFAULT 0, /* 급여 */
	PROFILE_IMG BLOB, /* 프로필_이미지 */
	REG_DATE DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID NUMBER(5), /* 등록자 */
	MOD_DATE DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID NUMBER(5) /* 수정자 */
);

COMMENT ON TABLE EXAMPLE IS '테이블 설계 예시';

COMMENT ON COLUMN EXAMPLE.ID IS '아이디';

COMMENT ON COLUMN EXAMPLE.NAME IS '이름';

COMMENT ON COLUMN EXAMPLE.BIRTH_DATE IS '생년월일';

COMMENT ON COLUMN EXAMPLE.SALARY IS '급여';

COMMENT ON COLUMN EXAMPLE.PROFILE_IMG IS '프로필_이미지';

COMMENT ON COLUMN EXAMPLE.REG_DATE IS '등록일';

COMMENT ON COLUMN EXAMPLE.REG_ID IS '등록자';

COMMENT ON COLUMN EXAMPLE.MOD_DATE IS '수정일';

COMMENT ON COLUMN EXAMPLE.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_EXAMPLE
	ON EXAMPLE (
		ID ASC
	);

ALTER TABLE EXAMPLE
	ADD
		CONSTRAINT PK_EXAMPLE
		PRIMARY KEY (
			ID
		);